server:
  port: 19093

spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: store-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false # sql 로깅
        format_sql: false # SQL 문 정렬하여 출력
        highlight_sql: false # SQL 문 색 부여
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true


naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: /store-service/v3/api-docs
  swagger-ui:
    path: /store-service/swagger-ui.html
