server:
  port: 19091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/


token:
  secret-key: ${JWT_SECRET_KEY}

spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: GATEWAY SERVICE
      - url: /user-service/v3/api-docs
        name: USER SERVICE
      - url: /auth-service/v3/api-docs
        name: AUTH SERVICE
      - url: /store-service/v3/api-docs
        name: STORE SERVICE
      - url: /order-service/v3/api-docs
        name: ORDER SERVICE
      - url: /delivery-service/v3/api-docs
        name: DELIVERY SERVICE
      - url: /coupon-service/v3/api-docs
        name: COUPON SERVICE
      - url: /rider-service/v3/api-docs
        name: RIDER SERVICE
